---
title: "My Sleep Data"
author: "Jane Chen"
date: "04 May 2017"
output: ioslides_presentation
---

## Load Libraries
```{r 1stChunk, echo = FALSE, message = FALSE, warning = FALSE, results = FALSE}
options(digits = 1)
install.packages("lubridate", repos = "http://cran.r-project.org"); library(lubridate)
install.packages("dplyr", repos = "http://cran.r-project.org"); library(dplyr)
install.packages("plotly", repos = "https://cran.r-project.org"); library(plotly)
```

## My Sleep Data

```{r Data, echo = FALSE}
setwd("~/Desktop/OneDrive/Documents/Data Science/Coursera Files/Course 09 Developing Data products/week3")
mySleep <- read.csv("mySleep.csv")
mySleep$Start.Time <- dmy_hm(mySleep$Start.Time)
mySleep$End.Time <- dmy_hm(mySleep$End.Time)
head(mySleep)
```
This is my sleep time from 18 September 2016 to 18 November 2016. 

***
```{r meanSleep, echo = FALSE}
for(i in 1:nrow(mySleep)) {
    if(date(mySleep$Start.Time[i]) == date(mySleep$End.Time[i])) {
         mySleep$Day[i] <- wday(date(mySleep$Start.Time[i])-1, label = TRUE)
    } else {
        mySleep$Day[i] <- wday(mySleep$Start.Time[i], label = TRUE)
    }
}
mySleep$Day <- wday(mySleep$Day, label = TRUE)
mySleep$Duration <- with(mySleep, End.Time - Start.Time)
meanSleep <- mySleep %>%
    group_by(Day) %>%
    summarise(Duration = mean(Duration)) %>%
    print()
```

## Plot

```{r plot, echo = FALSE}
plot_ly(mySleep, x = ~Day, y = ~Duration, type = "scatter", mode = "markers")
```